language: node_js
node_js: 8

script:
  - npm run lint
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
    - npm run release

after_success: npm run coverage